# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone CoreUpdate" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release\drone-coreupdate.exe c:\drone-coreupdate.exe
ENTRYPOINT [ "c:\\drone-coreupdate.exe" ]
